version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 20
    commands:
      - echo "=== Install backend dependencies ==="
      - pip install --upgrade pip
      - pip install -r backend/requirements.txt

      - echo "=== Install frontend dependencies ==="
      - cd frontend
      - npm ci
      - cd ..
  pre_build:
    commands:
      - echo "=== Skipping tests in CI ==="
  build:
    commands:
      - echo "=== Build React frontend ==="
      - cd frontend
      - npm run build
      - cd ..

      - echo "=== Prepare Django static for React ==="
      - rm -rf backend/static/*
      - mkdir -p backend/static/js backend/static/css backend/static/media

      # JS / CSS / media from CRA build
      - cp -r frontend/build/static/js/* backend/static/js/ || true
      - cp -r frontend/build/static/css/* backend/static/css/ || true
      - cp -r frontend/build/static/media/* backend/static/media/ || true

      # Root HTML + misc files
      - cp frontend/build/index.html backend/static/index.html
      - cp frontend/build/asset-manifest.json backend/static/asset-manifest.json || true
      - cp frontend/build/favicon.ico backend/static/favicon.ico || true
      - cp frontend/build/manifest.json backend/static/manifest.json || true
      - cp frontend/build/robots.txt backend/static/robots.txt || true

      - echo "=== Collect Django static files ==="
      - cd backend
      - python manage.py collectstatic --noinput
      - cd ..

artifacts:
  files:
    - '**/*'
  discard-paths: no
