version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 20
    commands:
      - echo "=== Install backend dependencies ==="
      - pip install --upgrade pip
      - pip install -r backend/requirements.txt

      - echo "=== Install frontend dependencies ==="
      - cd frontend
      - npm ci
      - cd ..
  pre_build:
    commands:
      - echo "=== Run backend tests ==="
      - cd backend
      - python manage.py test || echo "Backend tests failed (non-blocking)"
      - cd ..

      - echo "=== Run frontend tests (optional) ==="
      - cd frontend
      - npm test -- --watch=false || echo "Frontend tests failed (non-blocking)"
      - cd ..
  build:
    commands:
      - echo "=== Build React frontend ==="
      - cd frontend
      - npm run build
      - cd ..

      - echo "=== Copy React build into Django static/frontend ==="
      - mkdir -p backend/static/frontend
      - cp -r frontend/build/* backend/static/frontend/

      - echo "=== Collect Django static files ==="
      - cd backend
      - python manage.py collectstatic --noinput
      - cd ..

artifacts:
  files:
    - '**/*'
  discard-paths: no
